apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  app: gitops-k8s
  app.kubernetes.io/owner.team: devops
  app.kubernetes.io/generated: "true"
fieldSpecs:
  - path: metadata/labels
    create: true
