---
# yaml-language-server:$schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-redis
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack
  path: ./cluster/apps/database/redis/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: common-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 15m
